# Generated by Django 5.1.15 on 2026-09-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("current_location", models.CharField(max_length=255)),
                ("pickup_location", models.CharField(max_length=255)),
                ("dropoff_location", models.CharField(max_length=255)),
                ("current_cycle_used_h", models.FloatField()),
                ("departure_at", models.DateTimeField()),
                ("use_split_sleeper", models.BooleanField(default=False)),
                ("driver_name", models.CharField(blank=True, max_length=255)),
                ("co_driver_name", models.CharField(blank=True, max_length=255)),
                ("carrier_name", models.CharField(blank=True, max_length=255)),
                ("main_office_address", models.CharField(blank=True, max_length=255)),
                ("home_terminal_address", models.CharField(blank=True, max_length=255)),
                ("tractor_number", models.CharField(blank=True, max_length=64)),
                ("trailer_number", models.CharField(blank=True, max_length=64)),
                ("shipper_name", models.CharField(blank=True, max_length=255)),
                ("commodity", models.CharField(blank=True, max_length=255)),
                ("shipping_doc_number", models.CharField(blank=True, max_length=128)),
                ("total_miles", models.FloatField(default=0)),
                ("total_drive_hours", models.FloatField(default=0)),
                ("total_duty_hours", models.FloatField(default=0)),
                ("total_days", models.PositiveIntegerField(default=0)),
                ("num_stops", models.PositiveIntegerField(default=0)),
                ("num_restarts", models.PositiveIntegerField(default=0)),
                ("route_is_estimate", models.BooleanField(default=False)),
                ("compliance_ok", models.BooleanField(default=True)),
                ("payload", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
